package updater

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// URL allowlist validation moved to internal/security. Tests live there.

// ════════════════════════════════════════════════════════════════════════════
// verifyChecksum — T-UPD-1
// ════════════════════════════════════════════════════════════════════════════

// sha256("hello") = 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
const helloSum = "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"

func writeTempFile(t *testing.T, content string) string {
	t.Helper()
	dir := t.TempDir()
	p := filepath.Join(dir, "test.bin")
	if err := os.WriteFile(p, []byte(content), 0600); err != nil {
		t.Fatalf("write temp: %v", err)
	}
	return p
}

func TestVerifyChecksum_match(t *testing.T) {
	p := writeTempFile(t, "hello")
	if err := verifyChecksum(p, helloSum); err != nil {
		t.Fatalf("expected match, got %v", err)
	}
}

func TestVerifyChecksum_uppercaseMatch(t *testing.T) {
	// verifyChecksum lowercases the expected hash before comparing, so
	// SHA256SUMS entries generated by `sha256sum` (lower) and
	// PowerShell `Get-FileHash` (upper) both work.
	p := writeTempFile(t, "hello")
	if err := verifyChecksum(p, strings.ToUpper(helloSum)); err != nil {
		t.Fatalf("expected uppercase match, got %v", err)
	}
}

func TestVerifyChecksum_mismatch(t *testing.T) {
	p := writeTempFile(t, "hello")
	bad := strings.Repeat("0", 64)
	err := verifyChecksum(p, bad)
	if err == nil {
		t.Fatal("expected mismatch error, got nil")
	}
	if !strings.Contains(err.Error(), "mismatch") {
		t.Fatalf("expected error to mention mismatch, got: %v", err)
	}
}

func TestVerifyChecksum_fileNotFound(t *testing.T) {
	err := verifyChecksum(filepath.Join(t.TempDir(), "does-not-exist"), helloSum)
	if err == nil {
		t.Fatal("expected file-not-found error, got nil")
	}
}

// ════════════════════════════════════════════════════════════════════════════
// parseSHA256SUMS — T-UPD-1 (SHA256SUMS line format)
// ════════════════════════════════════════════════════════════════════════════

const testSumsBody = `# header comment
deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef  TaskFlowDesktop-Setup-1.2.3.exe
cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe *TaskFlow-1.2.3-x86_64.AppImage
0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef  ./subdir/TaskFlowDesktop-1.2.3-universal.dmg

# trailing blank + comment should be ignored
`

func TestParseSHA256SUMS_textMode(t *testing.T) {
	got, err := parseSHA256SUMS(testSumsBody, "TaskFlowDesktop-Setup-1.2.3.exe")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	want := "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
	if got != want {
		t.Fatalf("got %q, want %q", got, want)
	}
}

func TestParseSHA256SUMS_binaryMode(t *testing.T) {
	// Leading `*` marks binary mode in sha256sum output — must be stripped.
	got, err := parseSHA256SUMS(testSumsBody, "TaskFlow-1.2.3-x86_64.AppImage")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	want := "cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe"
	if got != want {
		t.Fatalf("got %q, want %q", got, want)
	}
}

func TestParseSHA256SUMS_leadingPath(t *testing.T) {
	// `./subdir/TaskFlowDesktop-1.2.3-universal.dmg` must match the basename.
	got, err := parseSHA256SUMS(testSumsBody, "TaskFlowDesktop-1.2.3-universal.dmg")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	want := "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	if got != want {
		t.Fatalf("got %q, want %q", got, want)
	}
}

func TestParseSHA256SUMS_missingEntry(t *testing.T) {
	_, err := parseSHA256SUMS(testSumsBody, "nothing.exe")
	if err == nil {
		t.Fatal("expected missing-entry error, got nil")
	}
	if !strings.Contains(err.Error(), "no checksum entry") {
		t.Fatalf("unexpected error wording: %v", err)
	}
}

func TestParseSHA256SUMS_malformedHash(t *testing.T) {
	// A hash shorter than 64 hex chars must be rejected — otherwise a
	// truncated or attacker-crafted SHA256SUMS could succeed verification.
	bad := "short  TaskFlow.exe\n"
	_, err := parseSHA256SUMS(bad, "TaskFlow.exe")
	if err == nil {
		t.Fatal("expected malformed-hash error, got nil")
	}
	if !strings.Contains(err.Error(), "malformed hash") {
		t.Fatalf("unexpected error wording: %v", err)
	}
}

func TestParseSHA256SUMS_emptyBody(t *testing.T) {
	_, err := parseSHA256SUMS("", "anything.exe")
	if err == nil {
		t.Fatal("expected error for empty body")
	}
}
